spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: c5a4a04c55b430
    password: fd19ecb4fbb710
    properties:
      mail:
        smtp:
          starttls: true