create table public.users
(
    id uuid not null
        constraint users_pkey
            primary key,
    created_at timestamp,
    deleted_at timestamp,
    email varchar(255) UNIQUE,
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    phone varchar(255),
    updated_at timestamp
);

alter table public.users owner to postgres;

create table public.email
(
    id uuid not null
        constraint email_pkey
            primary key,
    last_sent_at timestamp,
    email_address varchar(255),
    sender_id uuid
        constraint fk80tal2wdl2v5akik95w5voo7j
            references public.users
);

alter table public.email owner to postgres;

create table public.user_roles
(
    id bigint generated by default as identity
        constraint user_roles_pkey
            primary key,
    role varchar(255),
    user_id uuid
        constraint fk5prxsdxrxjmldl8u51kc11y3e
            references public.users
);

alter table public.user_roles owner to postgres;